# Generated by Django 4.2.4 on 2023-08-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_red_green_blue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red',
            name='name',
        ),
    ]
