# Generated by Django 4.2.4 on 2023-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_remove_red_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='first_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='red',
            name='last_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
