# Generated by Django 4.2.4 on 2023-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_red_first_name_red_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='is_activae',
            field=models.BooleanField(default=False),
        ),
    ]
