# Generated by Django 4.2.4 on 2023-08-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_red_is_activae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='green',
            name='name',
        ),
    ]
