# Generated by Django 4.2.4 on 2023-08-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_green_first_name_green_is_activae_green_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blue',
            name='name',
        ),
    ]
