# Generated by Django 4.2.4 on 2023-08-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='posted_date',
        ),
    ]
