# Generated by Django 4.2.4 on 2023-08-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_remove_events_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
