# Generated by Django 4.2.4 on 2023-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_events_image_events_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.events')),
            ],
        ),
    ]
