# Generated by Django 4.2.4 on 2023-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_sportsmembers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='green',
            name='sports_item',
            field=models.BooleanField(default=False),
        ),
    ]
