# Generated by Django 4.2.4 on 2023-08-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0018_green_sports_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='green',
            name='cricket_item',
            field=models.BooleanField(default=False),
        ),
    ]
