# Generated by Django 4.2.4 on 2023-08-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_green_cricket_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='green',
            name='cricket_item',
        ),
    ]
