# Generated by Django 4.2.4 on 2023-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0020_remove_green_cricket_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='blue',
            name='sports_item',
            field=models.BooleanField(default=False),
        ),
    ]
