# Generated by Django 4.2.4 on 2023-08-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0022_red_sports_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentevnt',
            name='event',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='StudentEvnt',
        ),
    ]
